# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

title: Shifting
email: mike <at> mikeebert.net
description: > # this means to ignore newlines until "baseurl:"
  Cyclist turned software developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikeebert.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mikeebert
github_username:  mikeebert

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
